### PR TITLE
fix: add missing services based on latest docker-compose.yml

### LINKED ISSUE #52: No events showing up in 1.13.2 (Sentry 21.4.1)
After getting my DB migrations settled, I found that no new events are showing up in the issue list.

I suspect this change as the root cause: https://github.com/getsentry/onpremise/commit/4d7021729bbea1d1dda89696e41b4e05c995bce8#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

Furthermore I am not sure if this also needs to be changed:
https://github.com/getsentry/onpremise/commit/aecc75b1c91370469d501f51b139b7b4997c0995#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

And this:
https://github.com/getsentry/onpremise/commit/35a45ea7ae64b05ccf6a0c2f5bcbbaf204766c61#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

And this:
https://github.com/getsentry/onpremise/commit/e0dde9c57b9c04791935c5455c4ddcb6024e8c1f#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

Please have a look - I am stuck here 🍺

### PR DESCRIPTION
**Pull request by nodomain**
This PR adds support for the newly introduced ecs execute-command that allows you to open a shell inside a container. I used this to issue snuba migrations commands that helped me to mitigate #49 and fix the issue of broken event ingesting introduced with 1.13.2 - hopefully fixes https://github.com/Rungutan/sentry-fargate-cf-stack/issues/52

@mariusmitrofan please have a look at the containers/tasks thoroughly - this is a "works for me" solution and I am not sure if I broke some of your initial assumptions.

### CODE REVIEW

**Comment by nodomain** [comment]
I think this is fine now. Please have a look :)

**Comment by mariusmitrofan** [comment]
@nodomain I tested your stack changes and was able to get "errors".

Any idea if "performance monitoring" also works?

**Comment by nodomain** [comment]
It does
image

**Comment by mariusmitrofan** [comment]
NICE! WP!

Should we merge it or do you need more time with this ?

**Review by mariusmitrofan — APPROVED** [review]

**Comment by nodomain** [comment]
Let's give it tonight. I'll ping you when feeling confident enough ;)

**Comment by mariusmitrofan** [comment]
Fine by me :)

**Comment by nodomain** [comment]
Still fighting some weird KeyErrors in the Lambda response which get Cloudformation stuck ... I hate it 😅

**Comment by mariusmitrofan** [comment]
Use a try/except block while playing around with custom lambda so that at least the stack does not get stuck

```
try:
  <Whatever>
except Exception as e:
  print(e)

```

PS: Just make sure the "same" response is pushed by Lambda so that resources don't get randomly deleted

**Comment by nodomain** [comment]
Thx for the hint but I only extended your existing function:
https://github.com/nodomain/sentry-fargate-cf-stack/commit/db62035639cba56c9641203cb4939e285e4c2476

It creates the new config revision for MSK and applies it as requested but then gets stuck in the "cleanup" phase of the CF update.

```
[ERROR] KeyError: 'log_retention_hours'
Traceback (most recent call last):
  File "/var/task/index.py", line 19, in lambda_handler
    log.retention.hours = {event['ResourceProperties']['log_retention_hours']}
```

Investigating. And learning ;)

**Comment by mariusmitrofan** [comment]
These are the only vars you can set -> https://docs.aws.amazon.com/msk/latest/developerguide/msk-configuration-properties.html

**Comment by nodomain** [comment]
I found the root cause. If you add new attributes to the `server_properties` dictionary it will call the `DELETE` event somehow after running CF with the new attributes missing which leads to the error.
I will now hard code the values into the lambda because they are not changing at all and are managed by the CloudFormation template nevertheless.

**Comment by nodomain** [comment]
I think I got it now. Please check also in your stack, especially also after changing the `KafkaLogRetentionHours` variable.
There is a weird case when it issues a `DELETE` event which turned to break the lambda because the config is still in use. Hence my creative way of catching the error and responding with `success` nevertheless. If you have a better idea, I am open for it :-)

**Review by mariusmitrofan — APPROVED** [review]

**Comment by mariusmitrofan** [comment]
Looks fine to me :)

**Pull request merged**
